apiVersion: batch/v1
kind: Job
metadata:
  name: eval-job-standard-etth1
  labels:
    app: ml-training
    job-type: evaluation
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: ml-training
        job-type: evaluation
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 {{PROJECT_ROOT}}/mlruns"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: mlruns-volume
          mountPath: "{{PROJECT_ROOT}}/mlruns"

      containers:
      - name: evaluator
        image: ml-pipeline-train:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mlruns-volume
          mountPath: "{{PROJECT_ROOT}}/mlruns"

        command:
        - /bin/bash
        - -c
        - |
          # [STANDARD] Evaluation
          cd {{PROJECT_ROOT}} && python -m mlproject.src.pipeline.dag_run eval \
            -e {{PROJECT_ROOT}}/mlproject/configs/experiments/{{EXPERIMENT_CONFIG}} \
            -p {{PROJECT_ROOT}}/mlproject/configs/pipelines/{{PIPELINE_CONFIG}} \
            -a latest

        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: PYTHONUNBUFFERED
          value: "1"

      volumes:
      - name: mlruns-volume
        hostPath:
          path: "{{PROJECT_ROOT}}/mlruns"
          type: DirectoryOrCreate
