apiVersion: v1
kind: Service
metadata:
  name: ml-prediction-service
spec:
  type: ClusterIP  # Dùng NodePort hoặc LoadBalancer nếu muốn public ra internet
  selector:
    app: ml-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
