experiment:
  name: 'tab_xgboost'
  type: 'classification'
  model: "xgboost"
  model_type: "ml"
  hyperparams:
    input_chunk_length: 24
    output_chunk_length: 6
    type: "clasification"
    args:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.05
      objective: "binary:logistic"
      eval_metric: "auc"
      early_stopping_round: 15
