experiment:
  name: 'tab_xgboost'
  type: 'regression'
  model: "xgboost"
  model_type: "ml"
  hyperparams:
    input_chunk_length: 24
    output_chunk_length: 6
    type: "regression"
    args:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.05
      objective: "reg:squarederror"
      eval_metric: "rmse"
      early_stopping_round: 15
