pipeline:
  name: conditional_branch_tune
  steps:
  - id: load_data
    type: data_loader
    enabled: true
  - id: preprocess
    type: preprocessor
    log_artifact: true
    artifact_type: preprocess
    enabled: true
    depends_on:
    - load_data
    is_train: true
  - id: tune_train_tft
    type: tuner
    enabled: true
    depends_on: []
    target_model_id: train_tft
  - id: tune_train_xgb
    type: tuner
    enabled: true
    depends_on: []
    target_model_id: train_xgb
  - id: model_selection
    type: branch
    enabled: true
    depends_on:
    - preprocess
    condition:
      key: data_size
      operator: '>'
      value: 100
    if_true:
      id: train_tft
      type: framework_model
      log_artifact: true
      artifact_type: model
      experiment_config: mlproject/configs/model/tft_ts.yaml
      wiring:
        inputs:
          data: preprocessed_data
        outputs:
          model: selected_model
          datamodule: selected_dm
      use_tuned_params: true
      tune_step_id: tune_train_tft
      depends_on:
      - tune_train_tft
    if_false:
      id: train_xgb
      type: framework_model
      log_artifact: true
      artifact_type: model
      experiment_config: mlproject/configs/model/xgboost_ts.yaml
      wiring:
        inputs:
          data: preprocessed_data
        outputs:
          model: selected_model
          datamodule: selected_dm
      use_tuned_params: true
      tune_step_id: tune_train_xgb
      depends_on:
      - tune_train_xgb
  - id: evaluate
    type: evaluator
    enabled: true
    depends_on:
    - model_selection
    wiring:
      inputs:
        model: selected_model
        datamodule: selected_dm
      outputs:
        metrics: evaluation_metrics
  - id: log_results
    type: logger
    enabled: true
    depends_on:
    - evaluate
    wiring:
      inputs:
        model: selected_model
        metrics: evaluation_metrics
