data:
  # train_path: "mlproject/data/ETTh1.csv"   # optional demo
  # test_path: "mlproject/data/ETTh1.csv"   # optional demo
  # val_path: "mlproject/data/ETTh1.csv"   # optional demo
  path: "mlproject/data/ETTh1.csv"   # optional demo
  index_col: "date"
  target_columns: ["HUFL","MUFL"]
  features: ["HUFL", "MUFL", "mobility_inflow"]
  return_type: pandas
  type: timeseries
