data:
  path: "mlproject/data/ETTh1.csv"   # optional demo
  index_col: "date"
  target_columns: ["HUFL","MUFL","HULL","LULL"]
  features: ["HUFL", "MUFL", "mobility_inflow"]
  return_type: pandas
  type: timeseries
